import { addIcons } from 'ionicons';
import {
  arrowBack,
  bookOutline,
  bookSharp,
  bookmarkOutline,
  bookmarkSharp,
  chevronBackOutline,
  chevronForwardOutline,
  chevronUpCircle,
  closeCircle,
  closeOutline,
  documentTextOutline,
  documentTextSharp,
  earthOutline,
  languageOutline,
  saveOutline,
  searchOutline,
  searchSharp,
  settingsOutline,
  settingsSharp,
  shareSocialOutline,
  textOutline,
  timeOutline,
  timeSharp,
  trashOutline,
} from 'ionicons/icons';

export const initializeAppIcons = () => {
  addIcons({
    arrowBack,
    bookOutline,
    bookSharp,
    bookmarkOutline,
    bookmarkSharp,
    chevronBackOutline,
    chevronForwardOutline,
    chevronUpCircle,
    closeOutline,
    closeCircle,
    documentTextOutline,
    documentTextSharp,
    earthOutline,
    languageOutline,
    saveOutline,
    searchOutline,
    searchSharp,
    settingsOutline,
    settingsSharp,
    shareSocialOutline,
    textOutline,
    timeOutline,
    timeSharp,
    trashOutline,
  });
};
