export const AllBooks = {
  KJV: [
    {
      name: 'Genesis',
      abbreviation: 'Gen',
      bookNumber: 1,
      chapters: 50,
      usfm: 'GEN',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Exodus',
      abbreviation: 'Exod',
      bookNumber: 2,
      chapters: 40,
      usfm: 'EXO',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Leviticus',
      abbreviation: 'Lev',
      bookNumber: 3,
      chapters: 27,
      usfm: 'LEV',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Numbers',
      abbreviation: 'Num',
      bookNumber: 4,
      chapters: 36,
      usfm: 'NUM',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Deuteronomy',
      abbreviation: 'Deut',
      bookNumber: 5,
      chapters: 34,
      usfm: 'DEU',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Joshua',
      abbreviation: 'Josh',
      bookNumber: 6,
      chapters: 24,
      usfm: 'JOS',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Judges',
      abbreviation: 'Judg',
      bookNumber: 7,
      chapters: 21,
      usfm: 'JDG',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Ruth',
      abbreviation: 'Ruth',
      bookNumber: 8,
      chapters: 4,
      usfm: 'RUT',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: '1 Samuel',
      abbreviation: '1 Sam',
      bookNumber: 9,
      chapters: 31,
      usfm: '1SA',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: '2 Samuel',
      abbreviation: '2 Sam',
      bookNumber: 10,
      chapters: 24,
      usfm: '2SA',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: '1 Kings',
      abbreviation: '1 Kgs',
      bookNumber: 11,
      chapters: 22,
      usfm: '1KI',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: '2 Kings',
      abbreviation: '2 Kgs',
      bookNumber: 12,
      chapters: 25,
      usfm: '2KI',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: '1 Chronicles',
      abbreviation: '1 Chr',
      bookNumber: 13,
      chapters: 29,
      usfm: '1CH',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: '2 Chronicles',
      abbreviation: '2 Chr',
      bookNumber: 14,
      chapters: 36,
      usfm: '2CH',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Ezra',
      abbreviation: 'Ezra',
      bookNumber: 15,
      chapters: 10,
      usfm: 'EZR',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Nehemiah',
      abbreviation: 'Neh',
      bookNumber: 16,
      chapters: 13,
      usfm: 'NEH',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Esther',
      abbreviation: 'Esth',
      bookNumber: 17,
      chapters: 10,
      usfm: 'EST',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Job',
      abbreviation: 'Job',
      bookNumber: 18,
      chapters: 42,
      usfm: 'JOB',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Psalm',
      abbreviation: 'Ps',
      bookNumber: 19,
      chapters: 150,
      usfm: 'PSA',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Proverbs',
      abbreviation: 'Prov',
      bookNumber: 20,
      chapters: 31,
      usfm: 'PRO',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Ecclesiastes',
      abbreviation: 'Eccl',
      bookNumber: 21,
      chapters: 12,
      usfm: 'ECC',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Song of Solomon',
      abbreviation: 'Song',
      bookNumber: 22,
      chapters: 8,
      usfm: 'SNG',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Isaiah',
      abbreviation: 'Isa',
      bookNumber: 23,
      chapters: 66,
      usfm: 'ISA',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Jeremiah',
      abbreviation: 'Jer',
      bookNumber: 24,
      chapters: 52,
      usfm: 'JER',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Lamentations',
      abbreviation: 'Lam',
      bookNumber: 25,
      chapters: 5,
      usfm: 'LAM',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Ezekiel',
      abbreviation: 'Ezek',
      bookNumber: 26,
      chapters: 48,
      usfm: 'EZK',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Daniel',
      abbreviation: 'Dan',
      bookNumber: 27,
      chapters: 12,
      usfm: 'DAN',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Hosea',
      abbreviation: 'Hos',
      bookNumber: 28,
      chapters: 14,
      usfm: 'HOS',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Joel',
      abbreviation: 'Joel',
      bookNumber: 29,
      chapters: 3,
      usfm: 'JOL',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Amos',
      abbreviation: 'Amos',
      bookNumber: 30,
      chapters: 9,
      usfm: 'AMO',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Obadiah',
      abbreviation: 'Obad',
      bookNumber: 31,
      chapters: 1,
      usfm: 'OBA',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Jonah',
      abbreviation: 'Jonah',
      bookNumber: 32,
      chapters: 4,
      usfm: 'JON',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Micah',
      abbreviation: 'Mic',
      bookNumber: 33,
      chapters: 7,
      usfm: 'MIC',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Nahum',
      abbreviation: 'Nah',
      bookNumber: 34,
      chapters: 3,
      usfm: 'NAM',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Habakkuk',
      abbreviation: 'Hab',
      bookNumber: 35,
      chapters: 3,
      usfm: 'HAB',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Zephaniah',
      abbreviation: 'Zeph',
      bookNumber: 36,
      chapters: 3,
      usfm: 'ZEP',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Haggai',
      abbreviation: 'Hag',
      bookNumber: 37,
      chapters: 2,
      usfm: 'HAG',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Zechariah',
      abbreviation: 'Zech',
      bookNumber: 38,
      chapters: 14,
      usfm: 'ZEC',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Malachi',
      abbreviation: 'Mal',
      bookNumber: 39,
      chapters: 4,
      usfm: 'MAL',
      canon: 'ot',
      translation: 'KJV',
    },
    {
      name: 'Matthew',
      abbreviation: 'Matt',
      bookNumber: 40,
      chapters: 28,
      usfm: 'MAT',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Mark',
      abbreviation: 'Mark',
      bookNumber: 41,
      chapters: 16,
      usfm: 'MRK',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Luke',
      abbreviation: 'Luke',
      bookNumber: 42,
      chapters: 24,
      usfm: 'LUK',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'John',
      abbreviation: 'John',
      bookNumber: 43,
      chapters: 21,
      usfm: 'JHN',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Acts',
      abbreviation: 'Acts',
      bookNumber: 44,
      chapters: 28,
      usfm: 'ACT',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Romans',
      abbreviation: 'Rom',
      bookNumber: 45,
      chapters: 16,
      usfm: 'ROM',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '1 Corinthians',
      abbreviation: '1 Cor',
      bookNumber: 46,
      chapters: 16,
      usfm: '1CO',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '2 Corinthians',
      abbreviation: '2 Cor',
      bookNumber: 47,
      chapters: 13,
      usfm: '2CO',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Galatians',
      abbreviation: 'Gal',
      bookNumber: 48,
      chapters: 6,
      usfm: 'GAL',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Ephesians',
      abbreviation: 'Eph',
      bookNumber: 49,
      chapters: 6,
      usfm: 'EPH',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Philippians',
      abbreviation: 'Phil',
      bookNumber: 50,
      chapters: 4,
      usfm: 'PHP',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Colossians',
      abbreviation: 'Col',
      bookNumber: 51,
      chapters: 4,
      usfm: 'COL',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '1 Thessalonians',
      abbreviation: '1 Thes',
      bookNumber: 52,
      chapters: 5,
      usfm: '1TH',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '2 Thessalonians',
      abbreviation: '2 Thes',
      bookNumber: 53,
      chapters: 3,
      usfm: '2TH',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '1 Timothy',
      abbreviation: '1 Tim',
      bookNumber: 54,
      chapters: 6,
      usfm: '1TI',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '2 Timothy',
      abbreviation: '2 Tim',
      bookNumber: 55,
      chapters: 4,
      usfm: '2TI',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Titus',
      abbreviation: 'Titus',
      bookNumber: 56,
      chapters: 3,
      usfm: 'TIT',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Philemon',
      abbreviation: 'Phlm',
      bookNumber: 57,
      chapters: 1,
      usfm: 'PHM',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Hebrews',
      abbreviation: 'Heb',
      bookNumber: 58,
      chapters: 13,
      usfm: 'HEB',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'James',
      abbreviation: 'Jas',
      bookNumber: 59,
      chapters: 5,
      usfm: 'JAS',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '1 Peter',
      abbreviation: '1 Pet',
      bookNumber: 60,
      chapters: 5,
      usfm: '1PE',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '2 Peter',
      abbreviation: '2 Pet',
      bookNumber: 61,
      chapters: 3,
      usfm: '2PE',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '1 John',
      abbreviation: '1 John',
      bookNumber: 62,
      chapters: 5,
      usfm: '1JN',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '2 John',
      abbreviation: '2 John',
      bookNumber: 63,
      chapters: 1,
      usfm: '2JN',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: '3 John',
      abbreviation: '3 John',
      bookNumber: 64,
      chapters: 1,
      usfm: '3JN',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Jude',
      abbreviation: 'Jude',
      bookNumber: 65,
      chapters: 1,
      usfm: 'JUD',
      canon: 'nt',
      translation: 'KJV',
    },
    {
      name: 'Revelation',
      abbreviation: 'Rev',
      bookNumber: 66,
      chapters: 22,
      usfm: 'REV',
      canon: 'nt',
      translation: 'KJV',
    },
  ],
  NB: [
    {
      bookNumber: 1,
      canon: 'ot',
      chapters: 50,
      name: '1 Mosebok',
      translation: 'NB',
      usfm: 'GEN',
    },
    {
      bookNumber: 2,
      canon: 'ot',
      chapters: 40,
      name: '2 Mosebok',
      translation: 'NB',
      usfm: 'EXO',
    },
    {
      bookNumber: 3,
      canon: 'ot',
      chapters: 27,
      name: '3 Mosebok',
      translation: 'NB',
      usfm: 'LEV',
    },
    {
      bookNumber: 4,
      canon: 'ot',
      chapters: 36,
      name: '4 Mosebok',
      translation: 'NB',
      usfm: 'NUM',
    },
    {
      bookNumber: 5,
      canon: 'ot',
      chapters: 34,
      name: '5 Mosebok',
      translation: 'NB',
      usfm: 'DEU',
    },
    {
      bookNumber: 6,
      canon: 'ot',
      chapters: 24,
      name: 'Josva',
      translation: 'NB',
      usfm: 'JOS',
    },
    {
      bookNumber: 7,
      canon: 'ot',
      chapters: 21,
      name: 'Dommerne',
      translation: 'NB',
      usfm: 'JDG',
    },
    {
      bookNumber: 8,
      canon: 'ot',
      chapters: 4,
      name: 'Rut',
      translation: 'NB',
      usfm: 'RUT',
    },
    {
      bookNumber: 9,
      canon: 'ot',
      chapters: 31,
      name: '1 Samuel',
      translation: 'NB',
      usfm: '1SA',
    },
    {
      bookNumber: 10,
      canon: 'ot',
      chapters: 24,
      name: '2 Samuel',
      translation: 'NB',
      usfm: '2SA',
    },
    {
      bookNumber: 11,
      canon: 'ot',
      chapters: 22,
      name: '1 Kongebok',
      translation: 'NB',
      usfm: '1KI',
    },
    {
      bookNumber: 12,
      canon: 'ot',
      chapters: 25,
      name: '2 Kongebok',
      translation: 'NB',
      usfm: '2KI',
    },
    {
      bookNumber: 13,
      canon: 'ot',
      chapters: 29,
      name: '1 Krønikebok',
      translation: 'NB',
      usfm: '1CH',
    },
    {
      bookNumber: 14,
      canon: 'ot',
      chapters: 36,
      name: '2 Krønikebok',
      translation: 'NB',
      usfm: '2CH',
    },
    {
      bookNumber: 15,
      canon: 'ot',
      chapters: 10,
      name: 'Esra',
      translation: 'NB',
      usfm: 'EZR',
    },
    {
      bookNumber: 16,
      canon: 'ot',
      chapters: 13,
      name: 'Nehemja',
      translation: 'NB',
      usfm: 'NEH',
    },
    {
      bookNumber: 17,
      canon: 'ot',
      chapters: 10,
      name: 'Ester',
      translation: 'NB',
      usfm: 'EST',
    },
    {
      bookNumber: 18,
      canon: 'ot',
      chapters: 42,
      name: 'Job',
      translation: 'NB',
      usfm: 'JOB',
    },
    {
      bookNumber: 19,
      canon: 'ot',
      chapters: 150,
      name: 'Salmene',
      translation: 'NB',
      usfm: 'PSA',
    },
    {
      bookNumber: 20,
      canon: 'ot',
      chapters: 31,
      name: 'Salomos Ordspråk',
      translation: 'NB',
      usfm: 'PRO',
    },
    {
      bookNumber: 21,
      canon: 'ot',
      chapters: 12,
      name: 'Forkynneren',
      translation: 'NB',
      usfm: 'ECC',
    },
    {
      bookNumber: 22,
      canon: 'ot',
      chapters: 8,
      name: 'Høysangen',
      translation: 'NB',
      usfm: 'SNG',
    },
    {
      bookNumber: 23,
      canon: 'ot',
      chapters: 66,
      name: 'Jesaja',
      translation: 'NB',
      usfm: 'ISA',
    },
    {
      bookNumber: 24,
      canon: 'ot',
      chapters: 52,
      name: 'Jeremia',
      translation: 'NB',
      usfm: 'JER',
    },
    {
      bookNumber: 25,
      canon: 'ot',
      chapters: 5,
      name: 'Klagesangene',
      translation: 'NB',
      usfm: 'LAM',
    },
    {
      bookNumber: 26,
      canon: 'ot',
      chapters: 48,
      name: 'Esekiel',
      translation: 'NB',
      usfm: 'EZK',
    },
    {
      bookNumber: 27,
      canon: 'ot',
      chapters: 12,
      name: 'Daniel',
      translation: 'NB',
      usfm: 'DAN',
    },
    {
      bookNumber: 28,
      canon: 'ot',
      chapters: 14,
      name: 'Hosea',
      translation: 'NB',
      usfm: 'HOS',
    },
    {
      bookNumber: 29,
      canon: 'ot',
      chapters: 3,
      name: 'Joel',
      translation: 'NB',
      usfm: 'JOL',
    },
    {
      bookNumber: 30,
      canon: 'ot',
      chapters: 9,
      name: 'Amos',
      translation: 'NB',
      usfm: 'AMO',
    },
    {
      bookNumber: 31,
      canon: 'ot',
      chapters: 1,
      name: 'Obadja',
      translation: 'NB',
      usfm: 'OBA',
    },
    {
      bookNumber: 32,
      canon: 'ot',
      chapters: 4,
      name: 'Jona',
      translation: 'NB',
      usfm: 'JON',
    },
    {
      bookNumber: 33,
      canon: 'ot',
      chapters: 7,
      name: 'Mika',
      translation: 'NB',
      usfm: 'MIC',
    },
    {
      bookNumber: 34,
      canon: 'ot',
      chapters: 3,
      name: 'Nahum',
      translation: 'NB',
      usfm: 'NAM',
    },
    {
      bookNumber: 35,
      canon: 'ot',
      chapters: 3,
      name: 'Habakkuk',
      translation: 'NB',
      usfm: 'HAB',
    },
    {
      bookNumber: 36,
      canon: 'ot',
      chapters: 3,
      name: 'Sefanja',
      translation: 'NB',
      usfm: 'ZEP',
    },
    {
      bookNumber: 37,
      canon: 'ot',
      chapters: 2,
      name: 'Haggai',
      translation: 'NB',
      usfm: 'HAG',
    },
    {
      bookNumber: 38,
      canon: 'ot',
      chapters: 14,
      name: 'Sakarja',
      translation: 'NB',
      usfm: 'ZEC',
    },
    {
      bookNumber: 39,
      canon: 'ot',
      chapters: 4,
      name: 'Malaki',
      translation: 'NB',
      usfm: 'MAL',
    },
    {
      bookNumber: 40,
      canon: 'nt',
      chapters: 28,
      name: 'Matteus',
      translation: 'NB',
      usfm: 'MAT',
    },
    {
      bookNumber: 41,
      canon: 'nt',
      chapters: 16,
      name: 'Markus',
      translation: 'NB',
      usfm: 'MRK',
    },
    {
      bookNumber: 42,
      canon: 'nt',
      chapters: 24,
      name: 'Lukas',
      translation: 'NB',
      usfm: 'LUK',
    },
    {
      bookNumber: 43,
      canon: 'nt',
      chapters: 21,
      name: 'Johannes',
      translation: 'NB',
      usfm: 'JHN',
    },
    {
      bookNumber: 44,
      canon: 'nt',
      chapters: 28,
      name: 'Apostlenes gjerninger',
      translation: 'NB',
      usfm: 'ACT',
    },
    {
      bookNumber: 45,
      canon: 'nt',
      chapters: 16,
      name: 'Romerne',
      translation: 'NB',
      usfm: 'ROM',
    },
    {
      bookNumber: 46,
      canon: 'nt',
      chapters: 16,
      name: '1 Korinter',
      translation: 'NB',
      usfm: '1CO',
    },
    {
      bookNumber: 47,
      canon: 'nt',
      chapters: 13,
      name: '2 Korinter',
      translation: 'NB',
      usfm: '2CO',
    },
    {
      bookNumber: 48,
      canon: 'nt',
      chapters: 6,
      name: 'Galaterne',
      translation: 'NB',
      usfm: 'GAL',
    },
    {
      bookNumber: 49,
      canon: 'nt',
      chapters: 6,
      name: 'Efeserne',
      translation: 'NB',
      usfm: 'EPH',
    },
    {
      bookNumber: 50,
      canon: 'nt',
      chapters: 4,
      name: 'Filipperne',
      translation: 'NB',
      usfm: 'PHP',
    },
    {
      bookNumber: 51,
      canon: 'nt',
      chapters: 4,
      name: 'Kolosserne',
      translation: 'NB',
      usfm: 'COL',
    },
    {
      bookNumber: 52,
      canon: 'nt',
      chapters: 5,
      name: '1 Tessaloniker',
      translation: 'NB',
      usfm: '1TH',
    },
    {
      bookNumber: 53,
      canon: 'nt',
      chapters: 3,
      name: '2 Tessaloniker',
      translation: 'NB',
      usfm: '2TH',
    },
    {
      bookNumber: 54,
      canon: 'nt',
      chapters: 6,
      name: '1 Timoteus',
      translation: 'NB',
      usfm: '1TI',
    },
    {
      bookNumber: 55,
      canon: 'nt',
      chapters: 4,
      name: '2 Timoteus',
      translation: 'NB',
      usfm: '2TI',
    },
    {
      bookNumber: 56,
      canon: 'nt',
      chapters: 3,
      name: 'Titus',
      translation: 'NB',
      usfm: 'TIT',
    },
    {
      bookNumber: 57,
      canon: 'nt',
      chapters: 1,
      name: 'Filemon',
      translation: 'NB',
      usfm: 'PHM',
    },
    {
      bookNumber: 58,
      canon: 'nt',
      chapters: 13,
      name: 'Hebreerne',
      translation: 'NB',
      usfm: 'HEB',
    },
    {
      bookNumber: 59,
      canon: 'nt',
      chapters: 5,
      name: 'Jakob',
      translation: 'NB',
      usfm: 'JAS',
    },
    {
      bookNumber: 60,
      canon: 'nt',
      chapters: 5,
      name: '1 Peter',
      translation: 'NB',
      usfm: '1PE',
    },
    {
      bookNumber: 61,
      canon: 'nt',
      chapters: 3,
      name: '2 Peter',
      translation: 'NB',
      usfm: '2PE',
    },
    {
      bookNumber: 62,
      canon: 'nt',
      chapters: 5,
      name: '1 Johannes',
      translation: 'NB',
      usfm: '1JN',
    },
    {
      bookNumber: 63,
      canon: 'nt',
      chapters: 1,
      name: '2 Johannes',
      translation: 'NB',
      usfm: '2JN',
    },
    {
      bookNumber: 64,
      canon: 'nt',
      chapters: 1,
      name: '3 Johannes',
      translation: 'NB',
      usfm: '3JN',
    },
    {
      bookNumber: 65,
      canon: 'nt',
      chapters: 1,
      name: 'Judas',
      translation: 'NB',
      usfm: 'JUD',
    },
    {
      bookNumber: 66,
      canon: 'nt',
      chapters: 22,
      name: 'Åpenbaringen',
      translation: 'NB',
      usfm: 'REV',
    },
  ],
};
